Socialmediaproj/Socialmediaproj/urls.py
from django.contrib import admin
from django.urls import path
from socialapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.articleList,name='article_list'),
    path('<id>/<slug>',views.articleDetail,name='article_detail'),
    path('article_create/',views.article_create,name='article_create'),
    path('login/',views.loginView,name='loginView'),
    path('logout/',views.logoutView,name='logoutView'),
    path('register/',views.registerView,name='registerview'),
    path('like_article/',views.like_article,name='like_article'),
    path('article_edit/<id>',views.article_edit,name='article_edit'),
    path('article_delete/<id>',views.article_delete,name='article_delete'),
    path('favourite_article/<id>',views.favourite_article,name='favourite_article'),
    path('favourites',views.article_favourite_list,name='article_favourite_list')
]

socialapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.CharField(max_length=100,blank=True,null=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    likes=models.ManyToManyField(User,related_name='likes',blank=True)
    favourite=models.ManyToManyField(User,related_name='favourite',blank=True)
    created_date=models.DateTimeField(max_length=50,auto_now_add=True)
    body=models.CharField(max_length=500)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail',args=[self.id,self.slug])

    def total_likes(self):
        return self.likes.count()

@receiver(pre_save,sender=Article)
def pre_save_slug(sender,**kwargs):
    slug1=slugify(kwargs['instance'].title)
    kwargs['instance'].slug=slug1

class Images(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    def __str__(self):
        return self.article.title + " Images "

#multiple comments posiable on single post is called ForeignKey
#multiple comments posiable on single user is called ForeignKey

class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    reply=models.ForeignKey('Comment',null=True,on_delete=models.CASCADE,related_name='replies')
    content=models.TextField(max_length=200)

templates/articleDetail.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
      {% include 'base.html' %}
  </head>
  <style media="screen">
    h3{
      color: blue;
    }
    .gallery{
      margin-top: 20px;
      margin-bottom: 20px;
    }
    img{
      height: 50%;
      width: 50%;
    }
  </style>
  <body>
    {% include 'navbar.html' %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-10">
          <h3>{{article.title|capfirst}}</h3>
          Created By: {{article.author|capfirst}}
          <hr>
          <p>{{article.body}}</p>

          <div class="row gallery">{% include 'images.html' %}</div>

          <div id="favourite-section">{% include 'favourite.html' %}</div>
          <div>{% include 'likes.html' %}</div>
          <div>{% include 'buttons.html' %}</div><br><br>

          <hr>
          <form method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            {% if request.user.is_authenticated %}
            <input type="submit" value="Comment" class="btn btn-lg btn-outline-success font-weight-bold">
            <input type="reset" value="Clear" class="btn btn-lg btn-outline-danger font-weight-bold">
            {% else %}
            <input type="submit" value="Comment" class="btn btn-lg btn-outline-success font-weight-bold">
            <input type="reset" value="Clear" class="btn btn-lg btn-outline-danger font-weight-bold">
            {% endif %}
          </form>

        <div class="main-comment-section">
          {{ comments.count }} Comment{{ comments|pluralize }}
            {% for comment in comments %}
            <blockquote class="blockquote">
              <p class="mb-0">{{ comment.content }}</p>
              <footer class="blockquote-footer">By <cite title="Source Title">{{ comment.user|capfirst }}</cite>
                  <button type="button" name="button" class="reply-btn btn-sm btn-outline-dark font-weight-bold">Reply</button>
              </footer>
            </blockquote>

            <div class="replaied-comments container mt-2" style="display:none">
              {% for reply in comment.replies.all %}
              <blockquote class="blockquote">
                <p class="mb-0"><small>{{ reply.content }}</small></p>
                <footer class="blockquote-footer"><small>By <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
                </footer>
              </blockquote>
              {% endfor %}
              <div class="form-group row">
                <form method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="comment_id" value="{{ comment.id }}">
                  {{ comment_form.as_p }}
                  {% if request.user.is_authenticated %}
                  <input type="submit" value="Submit" class="btn btn-lg btn-outline-success font-weight-bold">
                  <input type="reset" value="Clear" class="btn btn-lg btn-outline-danger font-weight-bold">
                  {% else %}
                  <input type="submit" value="Submit" class="btn btn-lg btn-outline-success font-weight-bold" disabled>
                  <input type="reset" value="Clear" class="btn btn-lg btn-outline-danger font-weight-bold" disabled>
                  {% endif %}
                </form>
              </div>
            </div>
            {% endfor %}
        </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/articleList.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
  </head>
  <style media="screen">
    h1{
      color: maroon;
      text-shadow: 0px 0px 5px blue;
    }
  </style>
  <body>
    {% include 'navbar.html' %}
    <div class="messages">
      {% if messages %}
      {% for message in messages %}
      <p class="alert alert-{{ message.tags }} text-center">
        {{ message }}
      </p>
      {% endfor %}
      {% endif %}
    </div>
    <div class="container-fluid">
      <h1 class="text-center font-weight-bold">NTH-Social Media Project</h1>
      <div class="row">
          {% for i in articles %}
            <div class="col-md-6">
            <div class="img-thumbnail mt-2">
            <a href="{{ i.get_absolute_url }}">{{i.title|capfirst}}</a>  <small style="float:right;">{{i.created_date}}</small><br>
            Author: {{i.author|capfirst}}<br>
            {{i.body}}
            </div>
          </div>
          {% empty %}
          <h2>The Article is not Available belongs to {{ request.GET.query }}</h2>
          {% endfor %}
        </div>
      </div>
      <br>
    <div class="container-fluid">
      <ul class="pagination">
        {% if articles.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page= {{ articles.previous_page_number }}"> &laquo;</a>
          </li>
          {% endif %}
          {% for p in articles.paginator.page_range %}
            {% if articles.number == p %}
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}></a>
          </li>
          {% endif %}
        {% endfor %}
        {% if articles.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page= {{ articles.next_page_number }}"> &raquo;</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </body>
</html>

templates/article_edit.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-5">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <center>
            <input type="Submit" value="Update" class="btn btn-outline-success">
            <input type="reset" value="Clear" class="btn btn-outline-primary">
            </center>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

templates/article_favourite_list.html
{% include 'cdnlines.html '%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style media="screen">
    h1{
      color: blue;
      text-shadow: 0px 0px 5px maroon;
    }
  </style>
  <body>
    {% block content %}
    <h1 class="text-center font-weight-bold">My Favourite Article</h1>
    <div class="container-fluid">
      <div class="row">
          {% for article in favourite_articles %}
            <div class="col-md-6">
            <div class="img-thumbnail mt-2">
      <a href="{{ article.get_absolute_url }}">{{article.title|capfirst}}</a>  <small style="float:right;">{{article.created_date}}</small><br>
            Author: {{article.author|capfirst}}<br>
            {{article.body}}
            </div>
            <br>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endblock %}
  </body>
</html>

templates/articlecreate.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {{ formset.as_p }}
            <center>
            <input type="Submit" value="Submit" class="btn btn-outline-success">
            <input type="reset" value="Clear" class="btn btn-outline-primary">
            </center>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

templates/base.html
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title></title>
    {% include 'cdnlines.html' %}
    <link  href="{% static 'css/styles.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <script type="text/javascript">
     $(documnet).ready(function(event){
       $('.reply-btn').click(function(){
         $(this).parent().parent().next('.replaied-comments').fadeToggle()
       });
     });
    </script>
  </body>
</html>

templates/buttons.html
{% if article.author == request.user %}
<div class="section_edit" style="float:right;">
  <a href="{% url 'article_edit' article.id %}" class="btn btn-lg btn-outline-success">Edit</a>
</div>
<div class="section_edit" style="float:right; margin-left:10px;">
  <a href="{% url 'article_delete' article.id %}" class="btn btn-lg btn-outline-primary">Delete</a>
</div>
{% endif %}

templates/cdnlines.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

templates/favourite.html
{% if is_favourite %}
<a href="{% url 'favourite_article' article.id %}" class="btn btn-lg btn-outline-seconadary">
  Favourite
</a>
{% else %}
<a href="{% url 'favourite_article' article.id %}" class="btn btn-lg btn-outline-primary">
  Not Favourite
</a>
{% endif %}

templates/images.html
{% for i in article.images_set.all %}
<div class="col-md-3">
  <img src="{{ i.image.url }}" class="img-thumbnail">
</div>
{% endfor %}

templates/likes.html
{{ total_likes }} Like {{ total_likes|pluralize }}
<form  method="POST" action="{% url 'like_article' %}">
  {% csrf_token %}
  {% if is_liked %}
  <button type="submit" name="article_id" value={{ article.id }} class="btn btn-lg btn-outline-danger">Dislike</button>
  {% else %}
  <button type="submit" name="article_id" value={{ article.id }} class="btn btn-lg btn-outline-primary">Like</button>
  {% endif %}
</form>

templates/loginform.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
  </head>
  <style media="screen">
    h2{
      color: green;
      text-shadow: 0px 0px 2px blue,0px 0px 2px red;
    }
    input[value]{
      margin-top: 10px;
    }
  </style>
  <body>
    <h2 class="text-center font-weight-bold">Login Here..</h2>
    <div class="container-fluid">
      <div class="row">
        <div class="offset-md-4 col-md-4">
          <form method="POST">
            {% csrf_token %}
            {{ form }}
            <center>
            <input type="Submit" value="Login" class="btn btn-lg btn-outline-secondary">
            <input type="reset" value="Clear" class="btn btn-lg btn-outline-primary">
            </center>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article_list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='query'>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
    <ul>
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span>Welcome {{ request.user|capfirst }}</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'article_create' %}">Create Article</a>
          <a class="dropdown-item" href="{% url 'article_favourite_list' %}">Favourite Article</a>
          <a class="dropdown-item" href="{% url 'logoutView' %}">Logout</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% else %}
      <a href="{% url 'loginView' %}">Login</a>
      {% endif %}
    </ul>
  </div>
</nav>

templates/registerform.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'cdnlines.html' %}
  </head>
  <style media="screen">
    input[value]{
      margin-top: 10px;
    }
  </style>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="offset-md-3 col-md-4">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <center>
            <input type="submit" value="Register" class="btn btn-lg btn-outline-primary">
            <input type="reset" value="Clear" class="btn btn-lg btn-outline-secondary">
            </center>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>